export const tokenData = [
  {
    id: 1,
    symbol: "BTC",
    name: "Bitcoin",
    price: "BTCUSDT",
    icon: "/icons/btc.png",
  },
  {
    id: 2,
    symbol: "ETH",
    name: "Ethereum",
    price: "ETHUSDT",
    icon: "/icons/eth.png",
  },
  {
    id: 3,
    symbol: "BNB",
    name: "BNB",
    price: "BNBUSDT",
    icon: "/icons/bnb.png",
  },
  {
    id: 4,
    symbol: "XRP",
    name: "Ripple",
    price: "XRPUSDT",
    icon: "/icons/xrp.png",
  },
  {
    id: 5,
    symbol: "SOL",
    name: "Solana",
    price: "SOLUSDT",
    icon: "/icons/sol.png",
  },
  {
    id: 6,
    symbol: "ADA",
    name: "Cardano",
    price: "ADAUSDT",
    icon: "/icons/ada.png",
  },
  {
    id: 7,
    symbol: "DOGE",
    name: "Dogecoin",
    price: "DOGEUSDT",
    icon: "/icons/doge.png",
  },
  {
    id: 8,
    symbol: "AVAX",
    name: "Avalanche",
    price: "AVAXUSDT",
    icon: "/icons/avax.png",
  },
  {
    id: 9,
    symbol: "TRX",
    name: "Tron",
    price: "TRXUSDT",
    icon: "/icons/trx.png",
  },
  {
    id: 10,
    symbol: "MATIC",
    name: "Ploygon",
    price: "MATICUSDT",
    icon: "/icons/matic.png",
  },
  {
    id: 11,
    symbol: "DOT",
    name: "Polkadot",
    price: "DOTUSDT",
    icon: "/icons/dot.png",
  },
  {
    id: 12,
    symbol: "WBTC",
    name: "Ploygon",
    price: "WBTCUSDT",
    icon: "/icons/wbtc.png",
  },
  {
    id: 13,
    symbol: "SHIB",
    name: "SHIBA INU",
    price: "SHIBUSDT",
    icon: "/icons/shib.png",
  },
  {
    id: 14,
    symbol: "LTC",
    name: "Litecoin",
    price: "LTCUSDT",
    icon: "/icons/ltc.png",
  },
  {
    id: 15,
    symbol: "BCH",
    name: "Bitcoin Cash",
    price: "BCHUSDT",
    icon: "/icons/bch.png",
  },
  {
    id: 16,
    symbol: "ATOM",
    name: "Cosmos",
    price: "ATOMUSDT",
    icon: "/icons/atom.png",
  },
  {
    id: 17,
    symbol: "UNI",
    name: "Uniswap",
    price: "UNIUSDT",
    icon: "/icons/uni.png",
  },
  {
    id: 18,
    symbol: "XLM",
    name: "Steller Lumens",
    price: "XLMUSDT",
    icon: "/icons/xlm.png",
  },
  {
    id: 19,
    symbol: "XMR",
    name: "Monero",
    price: "XMRUSDT",
    icon: "/icons/xmr.png",
  },
  {
    id: 20,
    symbol: "ETC",
    name: "Ethereum Classic",
    price: "ETCUSDT",
    icon: "/icons/etc.png",
  },
  {
    id: 21,
    symbol: "NEAR",
    name: "Near Protocol",
    price: "NEARUSDT",
    icon: "/icons/near.png",
  },
  {
    id: 22,
    symbol: "RUNE",
    name: "THORChain",
    price: "RUNEUSDT",
    icon: "/icons/rune.png",
  },
  {
    id: 23,
    symbol: "HBAR",
    name: "Hedera Hashgraph",
    price: "HBARUSDT",
    icon: "/icons/hbar.png",
  },
  {
    id: 24,
    symbol: "FIL",
    name: "FILE",
    price: "FILUSDT",
    icon: "/icons/fil.png",
  },
  {
    id: 25,
    symbol: "ICP",
    name: "Internet Computer",
    price: "ICPUSDT",
    icon: "/icons/icp.png",
  },
  {
    id: 26,
    symbol: "APT",
    name: "Aptos",
    price: "APTUSDT",
    icon: "/icons/apt.png",
  },
  {
    id: 27,
    symbol: "LDO",
    name: "Lido DAO",
    price: "LDOUSDT",
    icon: "/icons/ldo.png",
  },
  {
    id: 28,
    symbol: "LINK",
    name: "Chain Link",
    price: "LINKUSDT",
    icon: "/icons/link.png",
  },
  {
    id: 29,
    symbol: "WBETH",
    name: "Wrapped Beacon ETH",
    price: "WBETHUSDT",
    icon: "/icons/wbeth.png",
  },
  {
    id: 30,
    symbol: "IMX",
    name: "ImmutableX",
    price: "IMXUSDT",
    icon: "/icons/imx.png",
  },
  {
    id: 31,
    symbol: "OP",
    name: "Optimism",
    price: "OPUSDT",
    icon: "/icons/op.png",
  },
  {
    id: 32,
    symbol: "GRT",
    name: "The Graph",
    price: "GRTUSDT",
    icon: "/icons/grt.png",
  },
  {
    id: 33,
    symbol: "TIA",
    name: "Celestia",
    price: "TIAUSDT",
    icon: "/icons/tia.png",
  },
  {
    id: 34,
    symbol: "STX",
    name: "Stacks",
    price: "STXUSDT",
    icon: "/icons/stx.png",
  },
  {
    id: 35,
    symbol: "INJ",
    name: "Injective",
    price: "INJUSDT",
    icon: "/icons/inj.png",
  },
  {
    id: 36,
    symbol: "FTT",
    name: "FTX Token",
    price: "FTTUSDT",
    icon: "/icons/ftt.png",
  },
  {
    id: 37,
    symbol: "RNDR",
    name: "Render Token",
    price: "RNDRUSDT",
    icon: "/icons/rndr.png",
  },
  {
    id: 38,
    symbol: "AAVE",
    name: "Aave",
    price: "AAVEUSDT",
    icon: "/icons/aave.png",
  },
  {
    id: 39,
    symbol: "ARB",
    name: "Arbitrum",
    price: "ARBUSDT",
    icon: "/icons/arb.png",
  },
  {
    id: 40,
    symbol: "MKR",
    name: "Maker",
    price: "MKRUSDT",
    icon: "/icons/mkr.png",
  },
  {
    id: 41,
    symbol: "ALGO",
    name: "Algorand",
    price: "ALGOUSDT",
    icon: "/icons/algo.jpg",
  },
  {
    id: 42,
    symbol: "LUNA",
    name: "Terra Classic",
    price: "LUNAUSDT",
    icon: "/icons/luna.png",
  },
  {
    id: 43,
    symbol: "FLOW",
    name: "Flow",
    price: "FLOWUSDT",
    icon: "/icons/flow.png",
  },
  {
    id: 44,
    symbol: "SNX",
    name: "Synthetix Network",
    price: "SNXUSDT",
    icon: "/icons/snx.png",
  },
  {
    id: 45,
    symbol: "THETA",
    name: "Theta Token",
    price: "THETAUSDT",
    icon: "/icons/theta.png",
  },
  {
    id: 46,
    symbol: "ORDI",
    name: "ORDI",
    price: "ORDIUSDT",
    icon: "/icons/ordi.png",
  },
  {
    id: 47,
    symbol: "AXS",
    name: "Axie Infinity",
    price: "AXSUSDT",
    icon: "/icons/axs.png",
  },
  {
    id: 48,
    symbol: "SAND",
    name: "The Sandbox",
    price: "SANDUSDT",
    icon: "/icons/sand.png",
  },
  {
    id: 49,
    symbol: "FTM",
    name: "Fantom",
    price: "FTMUSDT",
    icon: "/icons/ftm.png",
  },
  {
    id: 50,
    symbol: "MANA",
    name: "Decentraland",
    price: "MANAUSDT",
    icon: "/icons/mana.png",
  },
];
